name: Deploy Server App

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy .env file
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Создаем пустой файл .env в нужной директории
            touch /var/www/humandrinks-server/.env
            # Копируем содержимое из /etc/envs/server.env в .env
            cat /etc/envs/server.env > /var/www/humandrinks-server/.env
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Stop process (if running)
        run: |
          if pm2 list | grep -q "server"; then
            pm2 delete server
          else
            echo "Server process not found, skipping delete"
          fi

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 20 || { echo "NVM or Node.js 20 not found, aborting"; exit 1; }

            cd /var/www/humandrinks-server
            git pull origin dev || { echo "Git pull failed, aborting"; exit 1; }
            npm install || { echo "npm install failed, aborting"; exit 1; }
            pm2 start ecosystem.config.js || { echo "pm2 start failed, aborting"; exit 1; }
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
